%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Dynare_mod_file_outputgap';
M_.dynare_version = '5.2';
oo_.dynare_version = '5.2';
options_.dynare_version = '5.2';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(8,1);
M_.exo_names_tex = cell(8,1);
M_.exo_names_long = cell(8,1);
M_.exo_names(1) = {'eps_r_t'};
M_.exo_names_tex(1) = {'eps\_r\_t'};
M_.exo_names_long(1) = {'eps_r_t'};
M_.exo_names(2) = {'eps_b_t'};
M_.exo_names_tex(2) = {'eps\_b\_t'};
M_.exo_names_long(2) = {'eps_b_t'};
M_.exo_names(3) = {'eps_v_t'};
M_.exo_names_tex(3) = {'eps\_v\_t'};
M_.exo_names_long(3) = {'eps_v_t'};
M_.exo_names(4) = {'eps_g_t'};
M_.exo_names_tex(4) = {'eps\_g\_t'};
M_.exo_names_long(4) = {'eps_g_t'};
M_.exo_names(5) = {'eps_a_t'};
M_.exo_names_tex(5) = {'eps\_a\_t'};
M_.exo_names_long(5) = {'eps_a_t'};
M_.exo_names(6) = {'eps_target_t'};
M_.exo_names_tex(6) = {'eps\_target\_t'};
M_.exo_names_long(6) = {'eps_target_t'};
M_.exo_names(7) = {'eps_eta_t'};
M_.exo_names_tex(7) = {'eps\_eta\_t'};
M_.exo_names_long(7) = {'eps_eta_t'};
M_.exo_names(8) = {'eps_s'};
M_.exo_names_tex(8) = {'eps\_s'};
M_.exo_names_long(8) = {'eps_s'};
M_.endo_names = cell(65,1);
M_.endo_names_tex = cell(65,1);
M_.endo_names_long = cell(65,1);
M_.endo_names(1) = {'x_t'};
M_.endo_names_tex(1) = {'x\_t'};
M_.endo_names_long(1) = {'x_t'};
M_.endo_names(2) = {'gamma_t'};
M_.endo_names_tex(2) = {'gamma\_t'};
M_.endo_names_long(2) = {'gamma_t'};
M_.endo_names(3) = {'k_t'};
M_.endo_names_tex(3) = {'k\_t'};
M_.endo_names_long(3) = {'k_t'};
M_.endo_names(4) = {'L_t'};
M_.endo_names_tex(4) = {'L\_t'};
M_.endo_names_long(4) = {'L_t'};
M_.endo_names(5) = {'dL_t'};
M_.endo_names_tex(5) = {'dL\_t'};
M_.endo_names_long(5) = {'dL_t'};
M_.endo_names(6) = {'mc_t'};
M_.endo_names_tex(6) = {'mc\_t'};
M_.endo_names_long(6) = {'mc_t'};
M_.endo_names(7) = {'R_t'};
M_.endo_names_tex(7) = {'R\_t'};
M_.endo_names_long(7) = {'R_t'};
M_.endo_names(8) = {'rk_t'};
M_.endo_names_tex(8) = {'rk\_t'};
M_.endo_names_long(8) = {'rk_t'};
M_.endo_names(9) = {'w_t'};
M_.endo_names_tex(9) = {'w\_t'};
M_.endo_names_long(9) = {'w_t'};
M_.endo_names(10) = {'w_star_t'};
M_.endo_names_tex(10) = {'w\_star\_t'};
M_.endo_names_long(10) = {'w_star_t'};
M_.endo_names(11) = {'f1_t'};
M_.endo_names_tex(11) = {'f1\_t'};
M_.endo_names_long(11) = {'f1_t'};
M_.endo_names(12) = {'f2_t'};
M_.endo_names_tex(12) = {'f2\_t'};
M_.endo_names_long(12) = {'f2_t'};
M_.endo_names(13) = {'vw_t'};
M_.endo_names_tex(13) = {'vw\_t'};
M_.endo_names_long(13) = {'vw_t'};
M_.endo_names(14) = {'eta_t'};
M_.endo_names_tex(14) = {'eta\_t'};
M_.endo_names_long(14) = {'eta_t'};
M_.endo_names(15) = {'y_t'};
M_.endo_names_tex(15) = {'y\_t'};
M_.endo_names_long(15) = {'y_t'};
M_.endo_names(16) = {'pi_t'};
M_.endo_names_tex(16) = {'pi\_t'};
M_.endo_names_long(16) = {'pi_t'};
M_.endo_names(17) = {'pi_star_t'};
M_.endo_names_tex(17) = {'pi\_star\_t'};
M_.endo_names_long(17) = {'pi_star_t'};
M_.endo_names(18) = {'target_t'};
M_.endo_names_tex(18) = {'target\_t'};
M_.endo_names_long(18) = {'target_t'};
M_.endo_names(19) = {'x1_t'};
M_.endo_names_tex(19) = {'x1\_t'};
M_.endo_names_long(19) = {'x1_t'};
M_.endo_names(20) = {'x2_t'};
M_.endo_names_tex(20) = {'x2\_t'};
M_.endo_names_long(20) = {'x2_t'};
M_.endo_names(21) = {'s_t'};
M_.endo_names_tex(21) = {'s\_t'};
M_.endo_names_long(21) = {'s_t'};
M_.endo_names(22) = {'lambda_r_t'};
M_.endo_names_tex(22) = {'lambda\_r\_t'};
M_.endo_names_long(22) = {'lambda_r_t'};
M_.endo_names(23) = {'c_t'};
M_.endo_names_tex(23) = {'c\_t'};
M_.endo_names_long(23) = {'c_t'};
M_.endo_names(24) = {'b_t'};
M_.endo_names_tex(24) = {'b\_t'};
M_.endo_names_long(24) = {'b_t'};
M_.endo_names(25) = {'bstar_t'};
M_.endo_names_tex(25) = {'bstar\_t'};
M_.endo_names_long(25) = {'bstar_t'};
M_.endo_names(26) = {'u_t'};
M_.endo_names_tex(26) = {'u\_t'};
M_.endo_names_long(26) = {'u_t'};
M_.endo_names(27) = {'mu_t'};
M_.endo_names_tex(27) = {'mu\_t'};
M_.endo_names_long(27) = {'mu_t'};
M_.endo_names(28) = {'v_t'};
M_.endo_names_tex(28) = {'v\_t'};
M_.endo_names_long(28) = {'v_t'};
M_.endo_names(29) = {'i_t'};
M_.endo_names_tex(29) = {'i\_t'};
M_.endo_names_long(29) = {'i_t'};
M_.endo_names(30) = {'kbar_t'};
M_.endo_names_tex(30) = {'kbar\_t'};
M_.endo_names_long(30) = {'kbar_t'};
M_.endo_names(31) = {'gdp_t'};
M_.endo_names_tex(31) = {'gdp\_t'};
M_.endo_names_long(31) = {'gdp_t'};
M_.endo_names(32) = {'g_t'};
M_.endo_names_tex(32) = {'g\_t'};
M_.endo_names_long(32) = {'g_t'};
M_.endo_names(33) = {'a_t'};
M_.endo_names_tex(33) = {'a\_t'};
M_.endo_names_long(33) = {'a_t'};
M_.endo_names(34) = {'g_gdp_t'};
M_.endo_names_tex(34) = {'g\_gdp\_t'};
M_.endo_names_long(34) = {'g_gdp_t'};
M_.endo_names(35) = {'g_c_t'};
M_.endo_names_tex(35) = {'g\_c\_t'};
M_.endo_names_long(35) = {'g_c_t'};
M_.endo_names(36) = {'g_i_t'};
M_.endo_names_tex(36) = {'g\_i\_t'};
M_.endo_names_long(36) = {'g_i_t'};
M_.endo_names(37) = {'g_w_t'};
M_.endo_names_tex(37) = {'g\_w\_t'};
M_.endo_names_long(37) = {'g_w_t'};
M_.endo_names(38) = {'g_gdp_obs'};
M_.endo_names_tex(38) = {'g\_gdp\_obs'};
M_.endo_names_long(38) = {'g_gdp_obs'};
M_.endo_names(39) = {'g_c_obs'};
M_.endo_names_tex(39) = {'g\_c\_obs'};
M_.endo_names_long(39) = {'g_c_obs'};
M_.endo_names(40) = {'g_i_obs'};
M_.endo_names_tex(40) = {'g\_i\_obs'};
M_.endo_names_long(40) = {'g_i_obs'};
M_.endo_names(41) = {'g_w_obs'};
M_.endo_names_tex(41) = {'g\_w\_obs'};
M_.endo_names_long(41) = {'g_w_obs'};
M_.endo_names(42) = {'L_obs'};
M_.endo_names_tex(42) = {'L\_obs'};
M_.endo_names_long(42) = {'L_obs'};
M_.endo_names(43) = {'pi_obs'};
M_.endo_names_tex(43) = {'pi\_obs'};
M_.endo_names_long(43) = {'pi_obs'};
M_.endo_names(44) = {'R_obs'};
M_.endo_names_tex(44) = {'R\_obs'};
M_.endo_names_long(44) = {'R_obs'};
M_.endo_names(45) = {'wBN'};
M_.endo_names_tex(45) = {'wBN'};
M_.endo_names_long(45) = {'wBN'};
M_.endo_names(46) = {'lambda_f_t'};
M_.endo_names_tex(46) = {'lambda\_f\_t'};
M_.endo_names_long(46) = {'lambda_f_t'};
M_.endo_names(47) = {'c_f_t'};
M_.endo_names_tex(47) = {'c\_f\_t'};
M_.endo_names_long(47) = {'c_f_t'};
M_.endo_names(48) = {'rk_f_t'};
M_.endo_names_tex(48) = {'rk\_f\_t'};
M_.endo_names_long(48) = {'rk_f_t'};
M_.endo_names(49) = {'u_f_t'};
M_.endo_names_tex(49) = {'u\_f\_t'};
M_.endo_names_long(49) = {'u_f_t'};
M_.endo_names(50) = {'mu_f_t'};
M_.endo_names_tex(50) = {'mu\_f\_t'};
M_.endo_names_long(50) = {'mu_f_t'};
M_.endo_names(51) = {'i_f_t'};
M_.endo_names_tex(51) = {'i\_f\_t'};
M_.endo_names_long(51) = {'i_f_t'};
M_.endo_names(52) = {'R_f_t'};
M_.endo_names_tex(52) = {'R\_f\_t'};
M_.endo_names_long(52) = {'R_f_t'};
M_.endo_names(53) = {'w_f_t'};
M_.endo_names_tex(53) = {'w\_f\_t'};
M_.endo_names_long(53) = {'w_f_t'};
M_.endo_names(54) = {'f1_f_t'};
M_.endo_names_tex(54) = {'f1\_f\_t'};
M_.endo_names_long(54) = {'f1_f_t'};
M_.endo_names(55) = {'f2_f_t'};
M_.endo_names_tex(55) = {'f2\_f\_t'};
M_.endo_names_long(55) = {'f2_f_t'};
M_.endo_names(56) = {'L_f_t'};
M_.endo_names_tex(56) = {'L\_f\_t'};
M_.endo_names_long(56) = {'L_f_t'};
M_.endo_names(57) = {'k_f_t'};
M_.endo_names_tex(57) = {'k\_f\_t'};
M_.endo_names_long(57) = {'k_f_t'};
M_.endo_names(58) = {'x_f_t'};
M_.endo_names_tex(58) = {'x\_f\_t'};
M_.endo_names_long(58) = {'x_f_t'};
M_.endo_names(59) = {'gamma_f_t'};
M_.endo_names_tex(59) = {'gamma\_f\_t'};
M_.endo_names_long(59) = {'gamma_f_t'};
M_.endo_names(60) = {'y_f_t'};
M_.endo_names_tex(60) = {'y\_f\_t'};
M_.endo_names_long(60) = {'y_f_t'};
M_.endo_names(61) = {'kbar_f_t'};
M_.endo_names_tex(61) = {'kbar\_f\_t'};
M_.endo_names_long(61) = {'kbar_f_t'};
M_.endo_names(62) = {'gdp_f_t'};
M_.endo_names_tex(62) = {'gdp\_f\_t'};
M_.endo_names_long(62) = {'gdp_f_t'};
M_.endo_names(63) = {'m_t'};
M_.endo_names_tex(63) = {'m\_t'};
M_.endo_names_long(63) = {'m_t'};
M_.endo_names(64) = {'AUX_EXPECT_LAG_1_367'};
M_.endo_names_tex(64) = {'AUX\_EXPECT\_LAG\_1\_367'};
M_.endo_names_long(64) = {'AUX_EXPECT_LAG_1_367'};
M_.endo_names(65) = {'AUX_ENDO_LAG_6_1'};
M_.endo_names_tex(65) = {'AUX\_ENDO\_LAG\_6\_1'};
M_.endo_names_long(65) = {'AUX_ENDO_LAG_6_1'};
M_.endo_partitions = struct();
M_.param_names = cell(30,1);
M_.param_names_tex = cell(30,1);
M_.param_names_long = cell(30,1);
M_.param_names(1) = {'phi'};
M_.param_names_tex(1) = {'phi'};
M_.param_names_long(1) = {'phi'};
M_.param_names(2) = {'alpha'};
M_.param_names_tex(2) = {'alpha'};
M_.param_names_long(2) = {'alpha'};
M_.param_names(3) = {'g_omega_ss100'};
M_.param_names_tex(3) = {'g\_omega\_ss100'};
M_.param_names_long(3) = {'g_omega_ss100'};
M_.param_names(4) = {'pss100'};
M_.param_names_tex(4) = {'pss100'};
M_.param_names_long(4) = {'pss100'};
M_.param_names(5) = {'Lss'};
M_.param_names_tex(5) = {'Lss'};
M_.param_names_long(5) = {'Lss'};
M_.param_names(6) = {'beta'};
M_.param_names_tex(6) = {'beta'};
M_.param_names_long(6) = {'beta'};
M_.param_names(7) = {'g_I'};
M_.param_names_tex(7) = {'g\_I'};
M_.param_names_long(7) = {'g_I'};
M_.param_names(8) = {'sigma'};
M_.param_names_tex(8) = {'sigma'};
M_.param_names_long(8) = {'sigma'};
M_.param_names(9) = {'theta'};
M_.param_names_tex(9) = {'theta'};
M_.param_names_long(9) = {'theta'};
M_.param_names(10) = {'ksi_p'};
M_.param_names_tex(10) = {'ksi\_p'};
M_.param_names_long(10) = {'ksi_p'};
M_.param_names(11) = {'h'};
M_.param_names_tex(11) = {'h'};
M_.param_names_long(11) = {'h'};
M_.param_names(12) = {'sigma_z'};
M_.param_names_tex(12) = {'sigma\_z'};
M_.param_names_long(12) = {'sigma_z'};
M_.param_names(13) = {'delta'};
M_.param_names_tex(13) = {'delta'};
M_.param_names_long(13) = {'delta'};
M_.param_names(14) = {'kappa'};
M_.param_names_tex(14) = {'kappa'};
M_.param_names_long(14) = {'kappa'};
M_.param_names(15) = {'ksi_w'};
M_.param_names_tex(15) = {'ksi\_w'};
M_.param_names_long(15) = {'ksi_w'};
M_.param_names(16) = {'chi'};
M_.param_names_tex(16) = {'chi'};
M_.param_names_long(16) = {'chi'};
M_.param_names(17) = {'rhoR'};
M_.param_names_tex(17) = {'rhoR'};
M_.param_names_long(17) = {'rhoR'};
M_.param_names(18) = {'rhoR2'};
M_.param_names_tex(18) = {'rhoR2'};
M_.param_names_long(18) = {'rhoR2'};
M_.param_names(19) = {'alpha_pi'};
M_.param_names_tex(19) = {'alpha\_pi'};
M_.param_names_long(19) = {'alpha_pi'};
M_.param_names(20) = {'alpha_y'};
M_.param_names_tex(20) = {'alpha\_y'};
M_.param_names_long(20) = {'alpha_y'};
M_.param_names(21) = {'alpha_gy'};
M_.param_names_tex(21) = {'alpha\_gy'};
M_.param_names_long(21) = {'alpha_gy'};
M_.param_names(22) = {'g_y'};
M_.param_names_tex(22) = {'g\_y'};
M_.param_names_long(22) = {'g_y'};
M_.param_names(23) = {'rhob'};
M_.param_names_tex(23) = {'rhob'};
M_.param_names_long(23) = {'rhob'};
M_.param_names(24) = {'rhov'};
M_.param_names_tex(24) = {'rhov'};
M_.param_names_long(24) = {'rhov'};
M_.param_names(25) = {'rhog'};
M_.param_names_tex(25) = {'rhog'};
M_.param_names_long(25) = {'rhog'};
M_.param_names(26) = {'rhoa'};
M_.param_names_tex(26) = {'rhoa'};
M_.param_names_long(26) = {'rhoa'};
M_.param_names(27) = {'rhoeta'};
M_.param_names_tex(27) = {'rhoeta'};
M_.param_names_long(27) = {'rhoeta'};
M_.param_names(28) = {'rho_target'};
M_.param_names_tex(28) = {'rho\_target'};
M_.param_names_long(28) = {'rho_target'};
M_.param_names(29) = {'rhom'};
M_.param_names_tex(29) = {'rhom'};
M_.param_names_long(29) = {'rhom'};
M_.param_names(30) = {'alphaBN'};
M_.param_names_tex(30) = {'alphaBN'};
M_.param_names_long(30) = {'alphaBN'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 65;
M_.param_nbr = 30;
M_.orig_endo_nbr = 63;
M_.aux_vars(1).endo_index = 64;
M_.aux_vars(1).type = 4;
M_.aux_vars(1).orig_expr = 'EXPECTATION(-1)(pi_t)';
M_.aux_vars(2).endo_index = 65;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 7;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'R_t(-1)';
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'g_gdp_obs'};
options_.varobs(2)  = {'g_c_obs'};
options_.varobs(3)  = {'g_i_obs'};
options_.varobs(4)  = {'g_w_obs'};
options_.varobs(5)  = {'L_obs'};
options_.varobs(6)  = {'pi_obs'};
options_.varobs(7)  = {'R_obs'};
options_.varobs_id = [ 38 39 40 41 42 43 44  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 64;
M_.eq_nbr = 65;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 23 0;
 0 24 0;
 0 25 0;
 1 26 0;
 0 27 0;
 0 28 0;
 2 29 0;
 0 30 88;
 3 31 0;
 0 32 89;
 0 33 90;
 0 34 91;
 4 35 0;
 5 36 0;
 0 37 0;
 0 38 92;
 0 39 0;
 6 40 0;
 0 41 93;
 0 42 94;
 7 43 0;
 0 44 95;
 8 45 96;
 0 46 0;
 9 47 0;
 0 48 0;
 0 49 97;
 10 50 0;
 11 51 98;
 12 52 0;
 13 53 0;
 14 54 0;
 15 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 16 67 0;
 0 68 99;
 17 69 100;
 0 70 101;
 0 71 0;
 0 72 102;
 18 73 103;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 19 83 0;
 0 84 0;
 20 85 0;
 21 86 0;
 22 87 0;]';
M_.nstatic = 31;
M_.nfwrd   = 12;
M_.npred   = 18;
M_.nboth   = 4;
M_.nsfwrd   = 16;
M_.nspred   = 22;
M_.ndynamic   = 34;
M_.dynamic_tmp_nbr = [47; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'lambda_r_t' ;
  2 , 'name' , 'b_t' ;
  3 , 'name' , 'rk_t' ;
  4 , 'name' , '4' ;
  5 , 'name' , 'mu_t' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'w_star_t' ;
  8 , 'name' , 'f1_t' ;
  9 , 'name' , 'f2_t' ;
  10 , 'name' , 'k_t' ;
  11 , 'name' , 'L_t' ;
  12 , 'name' , 'gamma_t' ;
  13 , 'name' , 'pi_star_t' ;
  14 , 'name' , 'x1_t' ;
  15 , 'name' , 'x2_t' ;
  16 , 'name' , '16' ;
  17 , 'name' , '17' ;
  18 , 'name' , 'y_t' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , 'gdp_t' ;
  22 , 'name' , 'kbar_t' ;
  23 , 'name' , 'R_t' ;
  24 , 'name' , '24' ;
  25 , 'name' , '25' ;
  26 , 'name' , 'vw_t' ;
  27 , 'name' , 'g_gdp_t' ;
  28 , 'name' , 'g_c_t' ;
  29 , 'name' , 'g_i_t' ;
  30 , 'name' , 'g_w_t' ;
  31 , 'name' , 'dL_t' ;
  32 , 'name' , 'lambda_f_t' ;
  33 , 'name' , 'rk_f_t' ;
  34 , 'name' , '34' ;
  35 , 'name' , 'mu_f_t' ;
  36 , 'name' , '36' ;
  37 , 'name' , 'w_f_t' ;
  38 , 'name' , 'f1_f_t' ;
  39 , 'name' , 'f2_f_t' ;
  40 , 'name' , 'k_f_t' ;
  41 , 'name' , 'L_f_t' ;
  42 , 'name' , 'gamma_f_t' ;
  43 , 'name' , 'y_f_t' ;
  44 , 'name' , 'x_f_t' ;
  45 , 'name' , '45' ;
  46 , 'name' , 'kbar_f_t' ;
  47 , 'name' , '47' ;
  48 , 'name' , 'gdp_f_t' ;
  49 , 'name' , 'eta_t' ;
  50 , 'name' , 'bstar_t' ;
  51 , 'name' , 'v_t' ;
  52 , 'name' , 'g_t' ;
  53 , 'name' , 'a_t' ;
  54 , 'name' , 'target_t' ;
  55 , 'name' , 'm_t' ;
  56 , 'name' , 'g_gdp_obs' ;
  57 , 'name' , 'g_c_obs' ;
  58 , 'name' , 'g_i_obs' ;
  59 , 'name' , 'g_w_obs' ;
  60 , 'name' , 'L_obs' ;
  61 , 'name' , 'pi_obs' ;
  62 , 'name' , 'R_obs' ;
  63 , 'name' , 'wBN' ;
};
M_.mapping.x_t.eqidx = [10 11 12 14 15 18 19 ];
M_.mapping.gamma_t.eqidx = [12 18 19 ];
M_.mapping.k_t.eqidx = [10 19 24 ];
M_.mapping.L_t.eqidx = [8 9 11 19 31 60 ];
M_.mapping.dL_t.eqidx = [31 ];
M_.mapping.mc_t.eqidx = [10 11 12 14 ];
M_.mapping.R_t.eqidx = [6 23 62 ];
M_.mapping.rk_t.eqidx = [3 5 10 ];
M_.mapping.w_t.eqidx = [8 9 11 17 26 30 ];
M_.mapping.w_star_t.eqidx = [7 8 9 17 26 ];
M_.mapping.f1_t.eqidx = [7 8 ];
M_.mapping.f2_t.eqidx = [7 9 ];
M_.mapping.vw_t.eqidx = [26 ];
M_.mapping.eta_t.eqidx = [8 38 49 ];
M_.mapping.y_t.eqidx = [18 20 21 ];
M_.mapping.pi_t.eqidx = [6 8 9 14 15 16 17 23 25 26 61 63 64 ];
M_.mapping.pi_star_t.eqidx = [13 16 25 ];
M_.mapping.target_t.eqidx = [23 54 ];
M_.mapping.x1_t.eqidx = [13 14 ];
M_.mapping.x2_t.eqidx = [13 15 ];
M_.mapping.s_t.eqidx = [10 11 12 19 25 ];
M_.mapping.lambda_r_t.eqidx = [1 4 5 6 9 14 15 ];
M_.mapping.c_t.eqidx = [1 20 28 ];
M_.mapping.b_t.eqidx = [1 2 32 ];
M_.mapping.bstar_t.eqidx = [2 50 ];
M_.mapping.u_t.eqidx = [3 20 21 24 ];
M_.mapping.mu_t.eqidx = [4 5 ];
M_.mapping.v_t.eqidx = [4 22 34 46 51 ];
M_.mapping.i_t.eqidx = [4 20 22 29 ];
M_.mapping.kbar_t.eqidx = [22 24 ];
M_.mapping.gdp_t.eqidx = [21 27 ];
M_.mapping.g_t.eqidx = [20 45 52 ];
M_.mapping.a_t.eqidx = [19 44 53 ];
M_.mapping.g_gdp_t.eqidx = [23 27 56 ];
M_.mapping.g_c_t.eqidx = [28 57 ];
M_.mapping.g_i_t.eqidx = [29 58 ];
M_.mapping.g_w_t.eqidx = [30 59 ];
M_.mapping.g_gdp_obs.eqidx = [56 ];
M_.mapping.g_c_obs.eqidx = [57 ];
M_.mapping.g_i_obs.eqidx = [58 ];
M_.mapping.g_w_obs.eqidx = [59 ];
M_.mapping.L_obs.eqidx = [60 ];
M_.mapping.pi_obs.eqidx = [61 ];
M_.mapping.R_obs.eqidx = [62 ];
M_.mapping.wBN.eqidx = [63 ];
M_.mapping.lambda_f_t.eqidx = [32 34 35 36 39 ];
M_.mapping.c_f_t.eqidx = [32 45 ];
M_.mapping.rk_f_t.eqidx = [33 35 40 ];
M_.mapping.u_f_t.eqidx = [33 45 47 48 ];
M_.mapping.mu_f_t.eqidx = [34 35 ];
M_.mapping.i_f_t.eqidx = [34 45 46 ];
M_.mapping.R_f_t.eqidx = [36 ];
M_.mapping.w_f_t.eqidx = [37 41 ];
M_.mapping.f1_f_t.eqidx = [37 38 ];
M_.mapping.f2_f_t.eqidx = [37 39 ];
M_.mapping.L_f_t.eqidx = [38 39 41 44 ];
M_.mapping.k_f_t.eqidx = [40 44 47 ];
M_.mapping.x_f_t.eqidx = [40 41 42 43 44 ];
M_.mapping.gamma_f_t.eqidx = [42 43 44 ];
M_.mapping.y_f_t.eqidx = [43 45 48 ];
M_.mapping.kbar_f_t.eqidx = [46 47 ];
M_.mapping.gdp_f_t.eqidx = [48 ];
M_.mapping.m_t.eqidx = [23 55 ];
M_.mapping.eps_r_t.eqidx = [55 ];
M_.mapping.eps_b_t.eqidx = [50 ];
M_.mapping.eps_v_t.eqidx = [51 ];
M_.mapping.eps_g_t.eqidx = [52 ];
M_.mapping.eps_a_t.eqidx = [53 ];
M_.mapping.eps_target_t.eqidx = [54 ];
M_.mapping.eps_eta_t.eqidx = [49 ];
M_.mapping.eps_s.eqidx = [63 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [4 7 9 13 14 18 21 23 25 28 29 30 31 32 33 45 47 51 61 63 64 65 ];
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(65, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(30, 1);
M_.endo_trends = struct('deflator', cell(65, 1), 'log_deflator', cell(65, 1), 'growth_factor', cell(65, 1), 'log_growth_factor', cell(65, 1));
M_.NNZDerivatives = [236; 0; -1; ];
M_.static_tmp_nbr = [47; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all;
M_.params(6) = 0.994;
beta = M_.params(6);
M_.params(13) = 0.025;
delta = M_.params(13);
M_.params(22) = 0.22;
g_y = M_.params(22);
M_.params(28) = 0.995;
rho_target = M_.params(28);
M_.params(8) = 6;
sigma = M_.params(8);
M_.params(9) = 6;
theta = M_.params(9);
M_.params(7) = 1.0037;
g_I = M_.params(7);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 2, 0.30, 0.01, NaN, 3, 0.30, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.5, 0.01, NaN, 3, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.5, NaN, NaN, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.0, NaN, NaN, 3, 0, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 1.0, NaN, NaN, 3, 0.75, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 2, NaN, NaN, 2, 2.0, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.5, NaN, NaN, 1, 0.66, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.5, NaN, NaN, 1, 0.66, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 5, NaN, NaN, 2, 5, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 4, NaN, NaN, 2, 4, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, 0.2, NaN, NaN, 1, 0.5, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.1, 0.01, NaN, 3, 0.13, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.1, 0.01, NaN, 3, 0.13, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.6, NaN, NaN, 3, 0.8, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, (-0.2), NaN, NaN, 3, (-0.1), 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 1.7, 0.01, NaN, 3, 1.1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.6, NaN, NaN, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.1, NaN, NaN, 4, 0.10, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.1, NaN, NaN, 4, 0.10, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.5, NaN, NaN, 4, 0.50, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.5, NaN, NaN, 4, 0.50, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.5, NaN, NaN, 4, 0.50, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.5, NaN, NaN, 4, 0.50, 1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.5, NaN, NaN, 4, 0.50, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 1.25, 0.5, 1.5, 5, NaN, NaN, 0.5, 1.5, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.10, 0.001, 120, 4, 0.1, 1.0, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 1, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 6, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 5, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 4, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 7, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 2, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
estim_params_.corrx = [estim_params_.corrx; 3, 8, 0.00, (-1), 1, 5, NaN, NaN, (-1), 1, NaN ];
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nodiagnostic = true;
options_.nograph = true;
options_.presample = 4;
options_.datafile = 'usdata_8407';
options_.order = 1;
var_list_ = {};
oo_recursive_=dynare_estimation(var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Dynare_mod_file_outputgap_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
